# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Design Research Is
tagline:          'Design research techniques and case studies'
description:      'Design research techniques and case studies'
url:              http://heyitsolivia.github.io/design-research
baseurl:          /design-research/

author:
  name:
  url:

paginate:         5

# Custom vars

github:
  repo:           https://github.com/heyitsolivia/design-research
