# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        none

# Setup
title:            Design Research Is
tagline:          'Design research techniques and case studies'
description:      'Design research techniques and case studies'
url:              http://designresearch.is
baseurl:

author:
  name:
  url:

paginate:         5

# Custom vars

github:
  repo:           https://github.com/codesignlab/design-research
